#!/usr/bin/env python3
"""Build the pinned athletic Vitruvian character with CharMorph and Rigify.

Run this script through Blender 4.5 LTS. The CharMorph add-on and Vitruvian
character library are intentionally external inputs; the generated Blender
file is an offline build artifact, not a runtime dependency of FitTimer.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import bpy

VITRUVIAN_COMMIT = "c252d1fc7f00ba59d87b66b3d32fa3471fc6ee44"
CHARMORPH_COMMIT = "e2e87480657c87eb17bbfbd83833bee628494a90"
ATHLETIC_FEMALE_MORPHS = {
    "Gender_Female": 1.0,
    "BodyType_Lean": 0.45,
    "BodyType_MesoMorph": 0.45,
    "BodyType_Muscular": 0.25,
    "Arms_BicepSize": 0.12,
    "Arms_Forearm_Girth": 0.08,
    "Arms_TricepSize": 0.12,
    "Legs_Calves_Size": 0.15,
    "Legs_Hamstring_Size": 0.15,
    "Legs_Quad_Size": 0.18,
    "Legs_Thigh_Size": 0.08,
    "Shoulders_ShoulderWidth": 0.08,
    "Waist_GluteSize": 0.12,
    "Waist_Hips_Width": 0.06,
    "Chest_Breast_Size": 0.12,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--addon-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument(
        "--texture-size", choices=("1K", "2K", "4K", "UL"), default="1K"
    )
    parser.add_argument("--replace", action="store_true")
    return parser.parse_args(sys.argv[sys.argv.index("--") + 1 :])


def require_pinned_runtime() -> None:
    if bpy.app.version[:2] != (4, 5):
        raise RuntimeError(
            f"CharMorph generation is pinned to Blender 4.5; got {bpy.app.version_string}"
        )


def enable_addons(addon_dir: Path) -> None:
    addon_dir = addon_dir.resolve()
    if not (addon_dir / "CharMorph" / "__init__.py").is_file():
        raise FileNotFoundError(f"CharMorph is missing from {addon_dir}")
    sys.path.insert(0, str(addon_dir))
    if bpy.ops.preferences.addon_enable(module="rigify") != {"FINISHED"}:
        raise RuntimeError("Could not enable Blender's bundled Rigify add-on")
    if bpy.ops.preferences.addon_enable(module="CharMorph") != {"FINISHED"}:
        raise RuntimeError("Could not enable CharMorph")


def build_character(texture_size: str) -> tuple[bpy.types.Object, bpy.types.Object]:
    from CharMorph.common import manager
    from CharMorph.lib.charlib import library

    library.load()
    if "Vitruvian" not in library.chars:
        raise RuntimeError(
            f"Vitruvian is absent from the CharMorph library at {library.dirpath}"
        )

    ui = bpy.context.window_manager.charmorph_ui
    ui.base_model = "Vitruvian"
    ui.use_sk = True
    ui.import_morphs = False
    ui.import_expressions = False
    ui.tex_downscale = texture_size
    if bpy.ops.charmorph.import_char() != {"FINISHED"}:
        raise RuntimeError("CharMorph could not import Vitruvian")

    manager.morpher.apply_morph_data(
        {"type": ["Default"], "morphs": ATHLETIC_FEMALE_MORPHS}, False
    )
    ui.rig = "rigify"
    ui.rigify_metarig_only = False
    ui.rigify_disable_ik_stretch = True
    ui.rigify_limit_ik = True
    ui.fin_morph = "SK"
    ui.fin_subdivision = "NO"
    # Vitruvian's rig drivers reference these keys. They are stripped only
    # after the rig has been generated by the retarget/export step.
    ui.fin_expressions = "CH"
    ui.fin_rig = True
    ui.fin_csmooth = True
    ui.fin_cs_limit = True
    ui.fin_cs_lenweight = False
    ui.fin_cs_morphing = False
    ui.fin_vg_cleanup = False
    if bpy.ops.charmorph.finalize() != {"FINISHED"}:
        raise RuntimeError("CharMorph could not finalize the Rigify body")

    body = bpy.data.objects.get("cm_vitruvian")
    rig = bpy.data.objects.get("cm_vitruvian_rig")
    if not body or body.type != "MESH" or not rig or rig.type != "ARMATURE":
        raise RuntimeError("Finalized Vitruvian body or Rigify armature is missing")
    if not all(name in rig.pose.bones for name in ("root", "thigh_fk.L", "head")):
        raise RuntimeError("Generated Rigify control surface is incomplete")

    provenance = {
        "kind": "fitTimerVitruvianCharacter",
        "character": "CharMorph Vitruvian",
        "characterCommit": VITRUVIAN_COMMIT,
        "generator": "CharMorph",
        "generatorCommit": CHARMORPH_COMMIT,
        "blender": bpy.app.version_string,
        "profile": "athletic-female-v1",
        "morphs": ATHLETIC_FEMALE_MORPHS,
    }
    body["fitTimerAvatar"] = provenance
    rig["fitTimerAvatar"] = provenance
    return body, rig


def main() -> None:
    args = parse_args()
    require_pinned_runtime()
    output = args.output.resolve()
    if output.exists() and not args.replace:
        raise FileExistsError(f"Refusing to replace existing artifact: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)

    bpy.ops.wm.read_factory_settings(use_empty=True)
    enable_addons(args.addon_dir)
    body, rig = build_character(args.texture_size)
    bpy.ops.wm.save_as_mainfile(filepath=str(output))
    if not output.is_file() or output.stat().st_size == 0:
        raise RuntimeError("Blender did not create the character artifact")
    print(
        json.dumps(
            {
                "ok": True,
                "output": str(output),
                "bytes": output.stat().st_size,
                "vertices": len(body.data.vertices),
                "rigBones": len(rig.data.bones),
                "blender": bpy.app.version_string,
                "profile": "athletic-female-v1",
            }
        )
    )


if __name__ == "__main__":
    main()
